//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Input/PlayerInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputs"",
    ""maps"": [
        {
            ""name"": ""GroundMap"",
            ""id"": ""fd5993ec-debb-4714-86a9-779c246dddf5"",
            ""actions"": [
                {
                    ""name"": ""Directions"",
                    ""type"": ""Value"",
                    ""id"": ""be91e8d0-827a-403f-b979-b32748f8add3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Aim"",
                    ""type"": ""PassThrough"",
                    ""id"": ""4a89f445-16e2-4bbb-8100-99d21dab66f9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""5db94cf5-a870-4f66-a5ed-5f73c15183ed"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.06,pressPoint=0.05)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryInteract"",
                    ""type"": ""Button"",
                    ""id"": ""c838dae5-50d7-48b9-bc0d-5517e8478519"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.06,pressPoint=0.05)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleRotate"",
                    ""type"": ""Button"",
                    ""id"": ""dd627db2-30b6-484f-a8c3-46d240f38974"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Button"",
                    ""id"": ""feae1db4-aefb-481b-8281-24e9eb5b5cc6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RhythmNotes"",
                    ""type"": ""Button"",
                    ""id"": ""ad6882b9-a3f0-48cc-be7f-3e2a95ab81ec"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector MNK"",
                    ""id"": ""23dcb759-c4b0-4995-b453-133bdb653352"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Directions"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ba65e840-6a5c-4854-84f6-79e0c38fc6f3"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Directions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""42e06b67-43b6-422e-981f-068377a73eb0"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Directions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4bcfe703-8e3b-4653-9b31-2b9547c704e0"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Directions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c7843094-5c53-419b-9741-03275057dffe"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Directions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""8f8c80c1-aa29-47dd-9ab3-2789a2adc488"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Directions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5afed25-b911-4da3-9ee6-8cdb009c433c"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""24d2102a-83ad-4bb5-994c-5b4aa700b66c"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""09e4d5fc-32e4-4ae1-b8c4-e22fd07ce89b"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""59eba3bb-154e-4952-9e86-20ddeb255d59"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f1445e42-1502-4cf2-aecd-43ec32f7c842"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleRotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""f59124bd-ab52-4aa8-9b35-4918e8e831e4"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""d31a4d2c-ad86-432a-a8de-c86113dd54a5"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""dc088b33-2986-4b78-8a6f-4bef5932f53c"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""26d3b0dc-54cb-4f21-bf37-d91efc954ea2"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryInteract"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b9cacfb-f7fa-42d4-bc09-9b8c5fd0f37e"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryInteract"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7d310b83-3cde-4fcd-8363-ef11d303d3ea"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RhythmNotes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e56db07d-d08b-40b0-9ef1-1c5678e40b52"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RhythmNotes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8425f64-360a-4a16-99a7-987c2a9dcdf3"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RhythmNotes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5cac5f2-2176-4ece-9130-531a0340a055"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RhythmNotes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4900af45-071c-4e42-b877-ad0b7d079b1d"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RhythmNotes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""119f82f8-5d4b-451c-89ee-31e6276e81ee"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RhythmNotes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8aa26cfa-236d-4ff2-9283-c953012dfc1b"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RhythmNotes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""RhythmMap"",
            ""id"": ""9c4d59b5-1bc7-42f0-a841-7a50283fa1d3"",
            ""actions"": [
                {
                    ""name"": ""RhythmNotes"",
                    ""type"": ""Button"",
                    ""id"": ""a7c6c469-e89d-43ce-ac69-8e4dbc814be1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Leave"",
                    ""type"": ""Button"",
                    ""id"": ""51a0c27a-dc9c-4517-bd21-a6281a72a572"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1a9e88f5-b3fb-4101-a7c3-47dc4f64e29a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RhythmNotes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4307eb62-46e1-43b6-a69b-13666e76b399"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RhythmNotes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c15cffbc-9d27-490d-a0b1-17c5fd0f472c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RhythmNotes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab15296f-9796-4a22-8442-67e5a5416b8b"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RhythmNotes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ef42d7d5-c16d-463a-842b-5b671cfc1e11"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RhythmNotes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8e17ccae-b343-4e4a-9461-fb5d2e71a492"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RhythmNotes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a11047ca-5327-4b18-80b3-a762be36f296"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RhythmNotes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f13f3259-e6b1-4bda-a727-3129363ac331"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Leave"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GroundMap
        m_GroundMap = asset.FindActionMap("GroundMap", throwIfNotFound: true);
        m_GroundMap_Directions = m_GroundMap.FindAction("Directions", throwIfNotFound: true);
        m_GroundMap_Aim = m_GroundMap.FindAction("Aim", throwIfNotFound: true);
        m_GroundMap_Interact = m_GroundMap.FindAction("Interact", throwIfNotFound: true);
        m_GroundMap_SecondaryInteract = m_GroundMap.FindAction("SecondaryInteract", throwIfNotFound: true);
        m_GroundMap_ToggleRotate = m_GroundMap.FindAction("ToggleRotate", throwIfNotFound: true);
        m_GroundMap_Zoom = m_GroundMap.FindAction("Zoom", throwIfNotFound: true);
        m_GroundMap_RhythmNotes = m_GroundMap.FindAction("RhythmNotes", throwIfNotFound: true);
        // RhythmMap
        m_RhythmMap = asset.FindActionMap("RhythmMap", throwIfNotFound: true);
        m_RhythmMap_RhythmNotes = m_RhythmMap.FindAction("RhythmNotes", throwIfNotFound: true);
        m_RhythmMap_Leave = m_RhythmMap.FindAction("Leave", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GroundMap
    private readonly InputActionMap m_GroundMap;
    private List<IGroundMapActions> m_GroundMapActionsCallbackInterfaces = new List<IGroundMapActions>();
    private readonly InputAction m_GroundMap_Directions;
    private readonly InputAction m_GroundMap_Aim;
    private readonly InputAction m_GroundMap_Interact;
    private readonly InputAction m_GroundMap_SecondaryInteract;
    private readonly InputAction m_GroundMap_ToggleRotate;
    private readonly InputAction m_GroundMap_Zoom;
    private readonly InputAction m_GroundMap_RhythmNotes;
    public struct GroundMapActions
    {
        private @PlayerInputs m_Wrapper;
        public GroundMapActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Directions => m_Wrapper.m_GroundMap_Directions;
        public InputAction @Aim => m_Wrapper.m_GroundMap_Aim;
        public InputAction @Interact => m_Wrapper.m_GroundMap_Interact;
        public InputAction @SecondaryInteract => m_Wrapper.m_GroundMap_SecondaryInteract;
        public InputAction @ToggleRotate => m_Wrapper.m_GroundMap_ToggleRotate;
        public InputAction @Zoom => m_Wrapper.m_GroundMap_Zoom;
        public InputAction @RhythmNotes => m_Wrapper.m_GroundMap_RhythmNotes;
        public InputActionMap Get() { return m_Wrapper.m_GroundMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GroundMapActions set) { return set.Get(); }
        public void AddCallbacks(IGroundMapActions instance)
        {
            if (instance == null || m_Wrapper.m_GroundMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GroundMapActionsCallbackInterfaces.Add(instance);
            @Directions.started += instance.OnDirections;
            @Directions.performed += instance.OnDirections;
            @Directions.canceled += instance.OnDirections;
            @Aim.started += instance.OnAim;
            @Aim.performed += instance.OnAim;
            @Aim.canceled += instance.OnAim;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @SecondaryInteract.started += instance.OnSecondaryInteract;
            @SecondaryInteract.performed += instance.OnSecondaryInteract;
            @SecondaryInteract.canceled += instance.OnSecondaryInteract;
            @ToggleRotate.started += instance.OnToggleRotate;
            @ToggleRotate.performed += instance.OnToggleRotate;
            @ToggleRotate.canceled += instance.OnToggleRotate;
            @Zoom.started += instance.OnZoom;
            @Zoom.performed += instance.OnZoom;
            @Zoom.canceled += instance.OnZoom;
            @RhythmNotes.started += instance.OnRhythmNotes;
            @RhythmNotes.performed += instance.OnRhythmNotes;
            @RhythmNotes.canceled += instance.OnRhythmNotes;
        }

        private void UnregisterCallbacks(IGroundMapActions instance)
        {
            @Directions.started -= instance.OnDirections;
            @Directions.performed -= instance.OnDirections;
            @Directions.canceled -= instance.OnDirections;
            @Aim.started -= instance.OnAim;
            @Aim.performed -= instance.OnAim;
            @Aim.canceled -= instance.OnAim;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @SecondaryInteract.started -= instance.OnSecondaryInteract;
            @SecondaryInteract.performed -= instance.OnSecondaryInteract;
            @SecondaryInteract.canceled -= instance.OnSecondaryInteract;
            @ToggleRotate.started -= instance.OnToggleRotate;
            @ToggleRotate.performed -= instance.OnToggleRotate;
            @ToggleRotate.canceled -= instance.OnToggleRotate;
            @Zoom.started -= instance.OnZoom;
            @Zoom.performed -= instance.OnZoom;
            @Zoom.canceled -= instance.OnZoom;
            @RhythmNotes.started -= instance.OnRhythmNotes;
            @RhythmNotes.performed -= instance.OnRhythmNotes;
            @RhythmNotes.canceled -= instance.OnRhythmNotes;
        }

        public void RemoveCallbacks(IGroundMapActions instance)
        {
            if (m_Wrapper.m_GroundMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGroundMapActions instance)
        {
            foreach (var item in m_Wrapper.m_GroundMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GroundMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GroundMapActions @GroundMap => new GroundMapActions(this);

    // RhythmMap
    private readonly InputActionMap m_RhythmMap;
    private List<IRhythmMapActions> m_RhythmMapActionsCallbackInterfaces = new List<IRhythmMapActions>();
    private readonly InputAction m_RhythmMap_RhythmNotes;
    private readonly InputAction m_RhythmMap_Leave;
    public struct RhythmMapActions
    {
        private @PlayerInputs m_Wrapper;
        public RhythmMapActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @RhythmNotes => m_Wrapper.m_RhythmMap_RhythmNotes;
        public InputAction @Leave => m_Wrapper.m_RhythmMap_Leave;
        public InputActionMap Get() { return m_Wrapper.m_RhythmMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RhythmMapActions set) { return set.Get(); }
        public void AddCallbacks(IRhythmMapActions instance)
        {
            if (instance == null || m_Wrapper.m_RhythmMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_RhythmMapActionsCallbackInterfaces.Add(instance);
            @RhythmNotes.started += instance.OnRhythmNotes;
            @RhythmNotes.performed += instance.OnRhythmNotes;
            @RhythmNotes.canceled += instance.OnRhythmNotes;
            @Leave.started += instance.OnLeave;
            @Leave.performed += instance.OnLeave;
            @Leave.canceled += instance.OnLeave;
        }

        private void UnregisterCallbacks(IRhythmMapActions instance)
        {
            @RhythmNotes.started -= instance.OnRhythmNotes;
            @RhythmNotes.performed -= instance.OnRhythmNotes;
            @RhythmNotes.canceled -= instance.OnRhythmNotes;
            @Leave.started -= instance.OnLeave;
            @Leave.performed -= instance.OnLeave;
            @Leave.canceled -= instance.OnLeave;
        }

        public void RemoveCallbacks(IRhythmMapActions instance)
        {
            if (m_Wrapper.m_RhythmMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IRhythmMapActions instance)
        {
            foreach (var item in m_Wrapper.m_RhythmMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_RhythmMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public RhythmMapActions @RhythmMap => new RhythmMapActions(this);
    public interface IGroundMapActions
    {
        void OnDirections(InputAction.CallbackContext context);
        void OnAim(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnSecondaryInteract(InputAction.CallbackContext context);
        void OnToggleRotate(InputAction.CallbackContext context);
        void OnZoom(InputAction.CallbackContext context);
        void OnRhythmNotes(InputAction.CallbackContext context);
    }
    public interface IRhythmMapActions
    {
        void OnRhythmNotes(InputAction.CallbackContext context);
        void OnLeave(InputAction.CallbackContext context);
    }
}
